### ISSUE TITLE
Memory dump selection behavior

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#72]
When you click on an address the selection overlaps into the memory byte field. Same thing happens when you click on a row in the ascii field. Also, when you type a digit with an address selected, the selection moves. I don't think either field should be selectable at all.

<img width="97" alt="memory-dump-bug" src="https://user-images.githubusercontent.com/6937032/57977521-044e7880-79af-11e9-8d94-f706e0cda323.png">

**Comment by Matthew-McRaven** [comment]
I made these fields selectable so that users may copy the text dump, as it would be difficult to re-create the text dump by hand.

The rendering bug is an artifact of how I drew the lines. It turns out table views don't take kindly to people drawing random lines through the middle of them. Which version of Qt / operating system is this occurring under?

**Comment by StanWarford** [comment]
Qt 5.12.3, MacOS 10.14.4.

I see now that you can select address field and/or byte field and/or ascii field and copy text to clipboard, and the copy does not include the border line. It is slick, but I don't see any use case for it. I think it would be fine to only have the memory byte field be selectable and copyable. It would also be consistent with the fact that it is the only part of the memory dump that is editable.

**Comment by Matthew-McRaven** [comment]
I’ll make those columns unselectable.

**Comment by Matthew-McRaven** [comment]
Fixed with 4523f6845c88152540faea5433eef244fbf141dc.
