### ISSUE TITLE
fig0640 trace tag warning missing

### ISSUE THREAD

**Issue by StanWarford** [StanWarford/pep9suite#80]
In pep9asm Figure 6.40
`guess:   .EQUATE 0           ;local variable #2d`
if you omit the format trace tag
`guess:   .EQUATE 0           ;local variable`
a blue warning message should be triggered on the `SUBSP` line. The code executes as expected without the visual debugger, but there should be a warning message.

**Comment by Matthew-McRaven** [comment]
This is now fixed in Pep/10.
However, Pep/10 uses an entirely different assembler architecture.
Let me see if I can come up with a minimum replicating example, and construct a bugfix.

**Comment by Matthew-McRaven** [comment]
The minimum program reproducing the error:
```
ADDSP   2,i         ;pop #guess
.END
```
The issue seems to be that any program lacking format tags (#1c, #2d) will not trigger our trace tag resolver.
I added code that will cause (malformed) programs only containing symbol trace tags to go through our trace tag resolver.

<img width="509" alt="Screen Shot 2019-11-05 at 23 17 05" src="https://user-images.githubusercontent.com/35609985/68267986-69ac2980-0022-11ea-93e2-9c7e3274b6ca.png">

This additional logic fixes this bug as expected.

**Comment by Matthew-McRaven** [comment]
Will you confirm that the latest version of master fixes this bug?

**Comment by StanWarford** [comment]
Tested, fixed.
